NAME	= AT&T_Telephone

CC		= c++
FLAGS	= -Wall -Wextra -Werror
RM		= rm

SRC		= 

all:	$(NAME)

$(NAME):	
			$(CC) $(FLAGS) $(SRC) -o $(NAME)

fclean:
		@$(RM) $(NAME)

re:		fclean all

.PHONE:	all fclean re